export enum ErrorCodes {
	CLIENT_CREDENTIALS_GRANT_FAILED = "CLIENT_CREDENTIALS_GRANT_FAILED",
	ACCESS_TOKEN_NOT_IN_CREDENTIALS_RESPONSE = "ACCESS_TOKEN_NOT_IN_CREDENTIALS_RESPONSE",
	REFRESH_TOKEN_NOT_IN_CREDENTIALS_RESPONSE = "ACCESS_TOKEN_NOT_IN_CREDENTIALS_RESPONSE",
	NO_HANDLER_FOUND_IN_LAMBDA = "NO_HANDLER_FOUND_IN_LAMBDA",
}
